#!/usr/bin/env bash
#
# Generate garmin/source/Secret.mc from a local token file.
#
#   scripts/make_secret.sh [TOKEN_FILE]     (default: ~/.config/garmin/marley_token)
#
# The token is a simulator convenience: on a real watch, set the "GitHub token"
# app setting through Garmin Connect instead. Both Secret.mc and the token file
# are gitignored, and this script never prints the value.

set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."

TOKEN_FILE=${1:-$HOME/.config/garmin/marley_token}
OUT=garmin/source/Secret.mc

if [[ -r $TOKEN_FILE ]]; then
  # Strip trailing newline/whitespace; reject anything that would break the
  # Monkey C string literal rather than emitting broken source.
  TOKEN=$(tr -d '\r\n' < "$TOKEN_FILE" | sed 's/[[:space:]]*$//')
  case $TOKEN in
    *'"'*|*'\'*) echo "error: token contains a quote or backslash" >&2; exit 1 ;;
  esac
  STATUS="token baked in (${#TOKEN} chars)"
else
  TOKEN=""
  STATUS="no token file at $TOKEN_FILE - building in viewer mode"
fi

cat > "$OUT" <<GEN
// GENERATED by scripts/make_secret.sh -- do not edit, do not commit.
// Empty in a clean checkout; populated locally for simulator testing.
module Secret {
    const GITHUB_TOKEN = "$TOKEN";
}
GEN
echo "$STATUS"
